// <auto-generated />
using CRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CRMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CRMSDbContext))]
    [Migration("20260529100000_AddNampFineractProductFields")]
    partial class AddNampFineractProductFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // BuildTargetModel is used by EF tooling only, not by MigrateAsync().
            // The authoritative model snapshot is in CRMSDbContextModelSnapshot.cs.
        }
    }
}
