// <auto-generated />
using CRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CRMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CRMSDbContext))]
    [Migration("20260813100000_AddNampViabilityMetrics")]
    partial class AddNampViabilityMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot maintained in CRMSDbContextModelSnapshot.cs
        }
    }
}
