// <auto-generated />
using System;
using CRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CRMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CRMSDbContext))]
    [Migration("20260627100000_AddCorporateLoanRestructureFields")]
    partial class AddCorporateLoanRestructureFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Full model state is maintained in CRMSDbContextModelSnapshot.cs.
            // This stub satisfies the EF Core migration attribute requirement.
        }
    }
}
